name: 'Github issue to Trello card'
description: 'Convert a github issue to a trello card when the issue is created.'
inputs:
  sample-secret:
    description: 'The sample secret stored on Github.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sample-secret }}