name: 'Github issue to Trello card'
description: 'Convert a github issue to a trello card when the issue is created.'
inputs:
  list-id:
    description: 'List ID added the card created.'
    required: true
  name:
    description: 'Name of the card created.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.list-id }}
    - ${{ inputs.name }}